directories:
  output: release
  buildResources: assets
appId: com.chunginlee.interviewcoder
productName: QuizCoze
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - package.json
      - electron/**/*
asar: true
compression: maximum
generateUpdatesFilesForAllChannels: true
mac:
  category: public.app-category.developer-tools
  target:
    - target: dmg
      arch:
        - x64
        - arm64
    - target: zip
      arch:
        - x64
        - arm64
    - target: dmg
      arch:
        - x64
        - arm64
    - target: zip
      arch:
        - x64
        - arm64
  artifactName: Interview-Coder-${arch}.${ext}
  icon: assets/icons/mac/logo_qz.icns
  protocols:
    name: interview-coder-protocol
    schemes:
      - interview-coder
win:
  target:
    - nsis
  icon: assets/icons/win/logo_qz.ico
  artifactName: ${productName}-Windows-${version}.${ext}
  protocols:
    name: interview-coder-protocol
    schemes:
      - interview-coder
  sign: null
  verifyUpdateCodeSignature: false
linux:
  target:
    - AppImage
  icon: assets/icons/png/icon-256x256.png
  artifactName: ${productName}-Linux-${version}.${ext}
  protocols:
    name: interview-coder-protocol
    schemes:
      - interview-coder
publish:
  - provider: github
    owner: ibttf
    repo: interview-coder
    private: false
    releaseType: release
extraMetadata:
  main: dist-electron/main.js
electronVersion: 37.2.1
