"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
require("electron");
require("path");
require("fs");
const main = require("./main-ErpVTpXx.js");
exports.clearQueues = main.clearQueues;
exports.createWindow = main.createWindow;
exports.deleteScreenshot = main.deleteScreenshot;
exports.getExtraScreenshotQueue = main.getExtraScreenshotQueue;
exports.getHasDebugged = main.getHasDebugged;
exports.getImagePreview = main.getImagePreview;
exports.getMainWindow = main.getMainWindow;
exports.getProblemInfo = main.getProblemInfo;
exports.getScreenshotHelper = main.getScreenshotHelper;
exports.getScreenshotQueue = main.getScreenshotQueue;
exports.getView = main.getView;
exports.hideMainWindow = main.hideMainWindow;
exports.isVisible = main.isVisible;
exports.moveWindowHorizontal = main.moveWindowHorizontal;
exports.moveWindowVertical = main.moveWindowVertical;
exports.setHasDebugged = main.setHasDebugged;
exports.setProblemInfo = main.setProblemInfo;
exports.setView = main.setView;
exports.setWindowDimensions = main.setWindowDimensions;
exports.showMainWindow = main.showMainWindow;
exports.state = main.state;
exports.takeScreenshot = main.takeScreenshot;
exports.toggleMainWindow = main.toggleMainWindow;
//# sourceMappingURL=main.js.map
